version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.5-jessie
    steps:
      - checkout
      - run: python3 -m venv venv
      - run: . venv/bin/activiate
      - run: pip3 install --upgrade pip
      - run: pip3 install -r requirements.txt
      - run: cd src/
      - run: python -m pytest