version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.5-jessie
    steps:
      - checkout
      - restore_cache:
        key: v1-{{ checksum "requirements.txt" }}
      - run:
          command: |
            mkdir -p ./venv
            virtualenv ./venv
            . ./venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            cd src/
            python -m pytest
      - save_cache:
        key: v1-{{ checksum "requirements.txt" }}
        paths:
          "venv"
  deploy:
    machine: true
    steps:
      - checkout
      - run: 
          command: |
            echo 'deploying on master'

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
