version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.5-jessie
    steps:
      - checkout
      - run:
          command: |
            mkdir -p ./venv
            virtualenv ./venv
            . ./venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            cd src/
            python -m pytest