version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.5-jessie
    steps:
      - checkout
      - run: 
        command: |
          python3 -m venv venv
          . venv/bin/activiate
          pip3 install --upgrade pip
          pip3 install -r requirements.txt
          cd src/
          python -m pytest