version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.5-jessie
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: cd src/
      - run: python -m pytest