version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.5-jessie
    steps:
      - checkout
      - run:
          command: |
            mkdir -p ./venv
            virtualenv ./venv
            . ./venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            cd src/
            cp config.example.py ./config.py
            python -m pytest
  
  deploy:
    machine: true
    steps:
      - checkout
      - run: 
          command: |
            echo 'deploying on master'

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
        requires:
          - build
        filters:
          branches:
            only: master