# Generated by Django 2.0.6 on 2018-07-25 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('author', models.TextField()),
                ('isbn', models.TextField()),
                ('edition', models.SmallIntegerField()),
                ('printing', models.SmallIntegerField()),
                ('cover', models.SmallIntegerField()),
                ('year_printed', models.SmallIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('condition', models.SmallIntegerField()),
                ('date_purchased', models.DateField()),
                ('location_purchased', models.TextField(blank=True, null=True)),
                ('amount_paid', models.IntegerField()),
                ('sell_price', models.IntegerField()),
                ('site_listed', models.SmallIntegerField(blank=True, null=True)),
                ('shelf_location', models.TextField()),
                ('removal_action', models.NullBooleanField()),
                ('date_removed', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
